### ISSUE TITLE
IndexError on the direction.py script

### ISSUE THREAD

**Issue by jsimba-99** [asdcid/Chroloplast-genome-assembly#4]
Hi, I am runing the post assembly script direction.py using an assembly from canu and found the following error:

[root@localhost genomas_cedrela]$ python3.8 direction.py /canu_results/c_odor_contigs.fasta
Traceback (most recent call last):
  File "direction.py", line 193, in <module>
    main()
  File "direction.py", line 182, in main
    outputFile  = sys.argv[2]
IndexError: list index out of range

My three contigs on the inputFile are 120, 23 and 55 kb, so dont know if this has something to do with the error

Im on the basics of programming and have no clue how to solve this

I  would appreciate your help

**Comment by asdcid** [comment]
Hi Jsimba,

You should give it the output path, for example: `python3.8 direction.py /canu_results/c_odor_contigs.fasta /canu_results/c_odor_contigs.merge.fasta`.

The `/canu_results/c_odor_contigs.merge.fasta` is the complete typical chloroplast genome that merges the LSC, 2XIR and SSC.

**Comment by jsimba-99** [comment]
Hi Weiwen,

Thanks for your quick response, I followed your comments by adding the output path and no get this new error:

$python3.8 direction.py /home/jaime_s/genomas_cedrela/canu_results/c_odor_contigs.fasta /canu_results/c_odor_contigs.merge.fasta

Traceback (most recent call last):
  File "direction.py", line 193, in <module>
    main()
  File "direction.py", line 184, in main
    seq, mark     = loadFile(inputFile)
  File "direction.py", line 33, in loadFile
    lsc = data['1']
 KeyError: '1'

Could it be an issue with the length of the sequences in the input file?

Many thanks

cheers,

**Comment by asdcid** [comment]
Hi Jsimba,

Actually, this pipeline is about how to repeat the snow gum cp assembly paper. Therefore, it might not fit every condition. If you just want to combine this three contig, you can send it to me and I can help you to combine them.

**Comment by jsimba-99** [comment]
Hi Weiwen,

Thanks for your help on this

Here is the file with the three contigs

Looking forward to hearing from you

Cheers,

Jaime Simbaqueba, PhD

**Comment by asdcid** [comment]
Hi Jsimba,

I haven't received the file. Could you send it to wei.wang@anu.edu.au?

Cheers,
R
